### ISSUE TITLE
Relax is "Not Installed"

### ISSUE THREAD

**Issue by KarlBishop** [ostark/craft-relax#5]
I installed, disabled, uninstalled and then reinstalled Relax a few weeks ago (I thought I did) but just now I happened to look at `/admin/settings/plugins` and at the bottom of the list I see Relax: "Not Installed".

I don't remember seeing an error when I reinstalled it. And the changes to my repo were as expected (they mirrored the original install):

- `"ostark/craft-relax": "^1.0",` was added to composer.json
- package details etc were added to composer.lock
- config/relax.php still exists from previous install
- plugin details were added to project.yaml:

      relax:
        edition: standard
        enabled: true
        schemaVersion: 1.0.0

...but it must have failed at the time. How can I fix it?

Some details
---

The site is running locally on Nitro 2.0.9 and Craft Pro 3.7.34.
If I click "Install" on the `/admin/settings/plugins` screen it shows an error notice: `⚠ Couldn’t install plugin`.
And if I run `nitro craft plugin/install relax` on the command line I see this output:

```
connecting to my-site.nitro
*** installing relax
    > create table queue_hashed ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'queue_hashed' already exists
The SQL being executed was: CREATE TABLE `queue_hashed` (
        `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `channel` varchar(255) NOT NULL DEFAULT 'queue',
        `job` longblob NOT NULL,
        `job_hash` varchar(64) NULL DEFAULT NULL,
        `description` text,
        `timePushed` int(11) NOT NULL,
        `ttr` int(11) NOT NULL,
        `delay` int(11) NOT NULL DEFAULT 0,
        `priority` int(11) UNSIGNED NOT NULL DEFAULT 1024,
        `dateReserved` datetime(0),
        `timeUpdated` int(11),
        `progress` smallint(6) NOT NULL DEFAULT 0,
        `progressLabel` varchar(255),
        `attempt` int(11),
        `fail` tinyint(1) DEFAULT FALSE,
        `dateFailed` datetime(0),
        `error` text
) ENGINE = InnoDb DEFAULT CHARACTER SET = utf8 (/app/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /app/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `q...')
#1 /app/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('CREATE TABLE `q...')
#2 /app/vendor/yiisoft/yii2/db/Migration.php(323): yii\db\Command->execute()
#3 /app/vendor/ostark/craft-relax/src/migrations/Install.php(34): yii\db\Migration->createTable('queue_hashed', Array)
#4 /app/vendor/craftcms/cms/src/db/Migration.php(53): ostark\Relax\migrations\Install->safeUp()
#5 /app/vendor/craftcms/cms/src/db/MigrationManager.php(232): craft\db\Migration->up(true)
#6 /app/vendor/craftcms/cms/src/base/Plugin.php(140): craft\db\MigrationManager->migrateUp(Object(ostark\Relax\migrations\Install))
#7 /app/vendor/craftcms/cms/src/services/Plugins.php(536): craft\base\Plugin->install()
#8 /app/vendor/craftcms/cms/src/console/controllers/PluginController.php(127): craft\services\Plugins->installPlugin('relax')
#9 [internal function]: craft\console\controllers\PluginController->actionInstall('relax')
#10 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#12 /app/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('install', Array)
#13 /app/vendor/craftcms/cms/src/console/Controller.php(221): yii\console\Controller->runAction('install', Array)
#14 /app/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('install', Array)
#15 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('plugin/install', Array)
#16 /app/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('plugin/install', Array)
#17 /app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('plugin/install', Array)
#18 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(craft\console\Request))
#19 /app/craft(23): yii\base\Application->run()
#20 {main}
*** failed to install relax.

Error: exit status 1
```

Would it work if I drop the 'queue_hashed' table and reinstall?

**Comment by ostark** [comment]
> Would it work if I drop the 'queue_hashed' table and reinstall?

Yes.
